#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 14 21:31:23 2018

@author: KACHING
"""

class Solution:
    def hasPathSum(self, root, s):
        """
        :type root: TreeNode
        :type sum: int
        :rtype: bool
        """
        if root==None:
            return False
        s=s-root.val
        if root.left==None and root.right==None:
            return s==0
        return self.hasPathSum(root.left,s) or self.hasPathSum(root.right,s)
        

